# Generated by Django 5.2.9 on 2025-12-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amis_python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
