# Generated by Django 3.1.3 on 2026-01-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amis_python', '0002_alter_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploader',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
