# Generated by Django 4.2.26 on 2025-12-15 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amis_python', '0002_remove_file_uploader_alter_file_file'),
        ('my_app', '0002_alter_domain_created_at_alter_domain_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amis_python.file', verbose_name='logo'),
        ),
    ]
